application: adminkun00
version: 5
api_version: 1
runtime: python

default_expiration: "1d"

handlers:
- url: /css
  static_dir: assets/css
- url: /javascripts
  static_dir: assets/javascripts
- url: /images
  static_dir: assets/images
- url: /pictures
  static_dir: assets/pictures
- url: /thumbs
  static_dir: assets/thumbs

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /fetch_adminkun_from_atmarkit
  script: main.py
  login: admin
  
- url: .*
  script: main.py
